---
project_name: reward
before:
  hooks:
    - go mod download
    - go generate ./...
    - go install github.com/go-bindata/go-bindata/...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: binary
release:
  extra_files:
    - glob: ./VERSION.txt
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
