{{- /* @formatter:off */ -}}

---
api:
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    network: reward
    defaultRule: "Host(`{{ `{{ .Name }}` }}.reward.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":{{ default "80" .reward_traefik_http_port }}"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":{{ default "443" .reward_traefik_https_port }}"
{{- if .reward_traefik_bind_additional_http_ports -}}
{{- range $i, $v := .reward_traefik_bind_additional_http_ports }}
  {{- printf "http-additional-%d:" $v | nindent 2 -}}
    {{- printf `address: ":%d"` $v | nindent 4 -}}
{{- end -}}
{{- end -}}
{{- if .reward_traefik_bind_additional_https_ports -}}
{{- range $i, $v := .reward_traefik_bind_additional_https_ports }}
  {{- printf "https-additional-%d:" $v | nindent 2 -}}
    {{- printf `address: ":%d"` $v | nindent 4 -}}
{{- end -}}
{{- end }}
log:
  level: info
global:
  checkNewVersion: false
  sendAnonymousUsage: false
