{{- /* @formatter:off */ -}}

version: "3.5"
services:
{{ if not ( isEnabled ( default false .reward_single_web_container )) }}
  nginx:
    environment:
      - NGINX_PUBLIC=/pub
      - NGINX_TEMPLATE=magento2[.]conf
{{ end }}

  php-fpm:
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ .reward_env_name }}-livereload.tls=true
      - traefik.http.routers.{{ .reward_env_name }}-livereload.priority=3
      - traefik.http.routers.{{ .reward_env_name }}-livereload.rule=
          (HostRegexp(`{subdomain:.+}.{{ .traefik_domain }}`) || Host(`{{ .traefik_domain }}`))
            && (Path(`/livereload.js`) || Path(`/livereload`))
      - traefik.http.routers.{{ .reward_env_name }}-livereload.service={{ .reward_env_name }}-livereload
      - traefik.http.services.{{ .reward_env_name }}-livereload.loadbalancer.server.port=35729
      - traefik.docker.network={{ .reward_env_name }}_default
      - dev.reward.container.name=php-fpm
      - dev.reward.environment.name={{ .reward_env_name }}
    environment:
      - MAGE_DEBUG_SHOW_ARGS=1
{{ if ( isEnabled ( default false .reward_single_web_container )) }}
      - NGINX_PUBLIC=/pub
      - NGINX_TEMPLATE=magento2[.]conf
{{ end }}

  php-debug:
    environment:
      - MAGE_DEBUG_SHOW_ARGS=1
