{{- /* @formatter:off */ -}}

version: "3.5"
services:
  rabbitmq:
    hostname: "{{ .reward_env_name }}-rabbitmq"
    image: {{ default "docker.io/rewardenv" .reward_docker_image_repo }}/rabbitmq:{{ default "3.8" .rabbitmq_version }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ .reward_env_name }}-rabbitmq.tls=true
      - traefik.http.routers.{{ .reward_env_name }}-rabbitmq.rule=Host(`rabbitmq.{{ .traefik_domain }}`)
      - traefik.http.services.{{ .reward_env_name }}-rabbitmq.loadbalancer.server.port=15672
      - traefik.docker.network={{ .reward_env_name }}_default
      - dev.reward.container.name=rabbitmq
      - dev.reward.environment.name={{ .reward_env_name }}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
{{- if isEnabled ( default false .rabbitmq_expose ) }}
    ports:
      - {{ default 5672 .rabbitmq_expose_target }}:5672
{{- end }}

volumes:
  rabbitmq:
