---
name: Docker Image Elasticsearch
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/elasticsearch/**
    branches:
    - develop
jobs:
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh "${BUILD_GROUP}"
      env:
        BUILD_GROUP: elasticsearch
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        PUSH: "true"
