---
name: Docker Image Redis
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/redis/**
    branches:
    - develop
jobs:
  redis:
    name: Redis
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh "${BUILD_GROUP}"
      env:
        BUILD_GROUP: redis
        DOCKER_USERNAME: ${{ secrets.DEV_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DEV_DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DEV_DOCKER_REPO }}
        PUSH: "true"
