---
name: Docker Image Varnish
on:
  #  schedule:
  #    - cron: "0 6 1 * *"
  push:
    paths:
      - images/.trigger
      - images/varnish/**
    branches:
      - develop
jobs:
  varnish:
    name: Varnish
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: varnish
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
          DEFAULT_BASE: "debian"
