---
name: Docker Image Redis
on:
  #  schedule:
  #    - cron: "0 6 1 * *"
  push:
    paths:
      - images/.trigger
      - images/redis/**
    branches:
      - develop
jobs:
  redis:
    name: Redis
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: redis
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
