---
name: Docker Image MariaDB
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/mariadb/**
    branches:
    - main
    - develop
jobs:
  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh "${BUILD_GROUP}"
      env:
        BUILD_GROUP: mariadb
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        PUSH: "true"
