---
name: Docker Image Nginx
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/nginx/**
    branches:
    - main
    - develop
jobs:
  nginx:
    name: Nginx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh "${BUILD_GROUP}"
      env:
        BUILD_GROUP: nginx
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        PUSH: "true"
