---
name: Docker Image RabbitMQ
on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    paths:
      - images/.trigger
      - images/rabbitmq/**
    branches:
      - main
jobs:
  rabbitmq:
    name: RabbitMQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: rabbitmq
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
